boulderbuddy/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("gymstats/", include('gymstats.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gymstats/urls.py
from django.urls import path, include

from . import views

app_name = 'gs'
urlpatterns = [

    path("accounts/", include("django.contrib.auth.urls")),

    # Autocomplete routes
    path('sector-autocomplete/', views.GymSectorAutocompleteView.as_view(), name='sector-autocomplete'),
    path('gym-autocomplete/', views.GymAutocompleteView.as_view(), name="gym-autocomplete"),
    path('problem-autocomplete/', views.ProblemAutocompleteView.as_view(), name="problem-autocomplete"),
    path('grade-autocomplete/', views.GradeAutocompleteView.as_view(), name="grade-autocomplete"),

    # Home Page
    path('', views.index, name='index'),
    path('home/', views.home, name="home"),

    # Profil Page
    path('profil/', views.profil, name="profil"),
    path('profil/edit/', views.profil_edit, name="profil-edit"),

    # Statistics
    path('statistics/', views.stats_searchbar, name="stats-searchbar"),
    path('statistics/results', views.stats_display, name="stats-searchresults"),
    path('statistics/json/<str:range_method>', views.range_stats, name="stats-json"),

    # Session
    path('session/add-new/', views.new_session, name="session-add-new"),
    path('session/<int:session_id>/add-problems/', views.add_session_problems, name="session-add-problems"),
    
    path('session/<int:session_id>/', views.session, name="session"),
    path('session/<int:session_id>/statistics/', views.session_statistics, name='session-statistics'),
    path('session/<int:session_id>/details', views.session_details, name="session-details"),

    # Gym views
    path('gyms/', views.gyms_homepage, name="gym-homepage"),
    path('gyms/<str:gym_abv>/', views.gym_details, name="gym"),
    path('gyms/<str:gym_abv>/problems/', views.problems_by_gym, name="gym-problems"),

    # Problem views
    path('problems/', views.problems_homepage, name="pb-homepage"),
    path('problems/<int:problem_id>/', views.problem_detail, name="pb-details"),
    path('problems/<int:problem_id>/review/', views.review_problem, name="pb-review"),
    path('problems/<int:problem_id>/ric/', views.evaluate_ric_problem, name="pb-ric"),
    path('problems/<int:problem_id>/rics/<int:ric_id>/', views.problem_ric, name="pb-ric-display"),
    path('problems/<int:problem_id>/reviews/<int:review_id>/', views.problem_review, name="pb-review-display"),
    path('problems/<int:problem_id>/reviews/', views.problem_reviews, name="pb-reviews"),
    path('problems/searchbar/', views.problem_searchbar, name="pb-searchbar"),
    path('problems/search-results', views.problem_search_results, name="pb-searchresults")
]

gymstats/forms.py
from typing import Any, Dict, Mapping, Optional, Type, Union
from django.core.files.base import File
from django.db.models.base import Model
from django.forms import ModelForm, Textarea
from django.forms.utils import ErrorList
from gymstats.models import Session, Climber, IndoorBoulder, Try, Climbable
from django import forms
from dal import autocomplete
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Row, Column, HTML, Submit, Button
from crispy_forms.bootstrap import AppendedText, PrependedAppendedText, PrependedText, FormActions



class ClimberForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Fieldset(
                'General',
                Row(
                    Column(PrependedText('name', '👤'), css_class="form-group ml-3 mr-4"),
                    Column(PrependedText('picture', '🏢'), css_class="form-group mb-1 mr-3"),
                )
            ),
            Fieldset(
                'Preferences',
                Row(
                    # Column(PrependedText("stats_preference", "📅"), css_class="mr-2"),
                    Column(PrependedText("month_hard_boulder_target", "🕒"), css_class="mr-2"),
                    Column(AppendedText('month_hour_target', "h"))
                )
            ),
            Fieldset(
                'Gyms',
                Column(PrependedText("preferred_gyms", ""), css_class="mr-2"),
            ),
            FormActions(
                Submit('save', 'Save changes', css_class="btn btn-light"),
                Button('cancel', 'Cancel')
            ),
        )

    class Meta:
        model = Climber
        fields = ["name", "picture", "month_hard_boulder_target", "month_hour_target", "preferred_gyms"]


class SessionForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Fieldset(
                'General',
                Row(
                    Column(PrependedText('climber', '👤'), css_class="form-group ml-3 mr-4"),
                    Column(PrependedText('gym', '🏢'), css_class="form-group mb-1 mr-3"),
                ),
                Column("partners", css_class="form-group"),
            ),
            Fieldset(
                'Time',
                Row(
                    Column(PrependedText("date", "📅"), css_class="mr-2"),
                    Column(PrependedText("time", "🕒"), css_class="mr-2"),
                    Column(AppendedText('duration', "h"))
                )
            ),
            Fieldset(
                'Data',
                PrependedText("shoes", "👟"),
                Row(
                    Column(PrependedText("sleep", "🛏️")),
                    Column(PrependedText("alcohol", "🍺")),
                )
            ),
            Fieldset(
                'Feelings',
                PrependedText("notes", "🗈"),
                PrependedText("overall_grade", "⭐"),
                Row(
                    Column(PrependedText("strength", "💪"), css_class="mr-2"),
                    Column(PrependedText("motivation", "🔥"), css_class="mr-2"),
                    Column(PrependedText('fear', "😨"))
                )
            ),
            FormActions(
                Submit('save', 'Save changes', css_class="btn btn-light"),
                Button('cancel', 'Cancel')
            ),
        )

    class Meta:
        model = Session
        fields = '__all__'

        widget = {
            "notes": Textarea(attrs={"cols": 150, "rows": 40}),
        }


class TryForm(ModelForm):
    class Meta:
        model = Try
        exclude = ()
        widgets = {
            'problem': autocomplete.ModelSelect2(url='gs:problem-autocomplete',
                                                attrs={'data-html': True},
                                                forward=['sector', 'gym', 'session']),
        }


class IndoorBoulderForm(ModelForm):
    class Meta:
        model = IndoorBoulder
        exclude = ("removed",)
        widgets = {
            'sector': autocomplete.ModelSelect2(url='gs:sector-autocomplete',
                                                attrs={'data-html': True},
                                                forward=['gym']),
            'gym': autocomplete.ModelSelect2(url="gs:gym-autocomplete"),
            'grade': autocomplete.Select2(url='gs:grade-autocomplete',
                                                forward=['gym'])
        }

gymstats/views.py
import calendar
from datetime import date, datetime
import re

from dal import autocomplete

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template import loader
from django.urls import reverse

from .forms import SessionForm, ClimberForm
from .models import IndoorBoulder, Gym, Review, Climber, Session, Try, RIC, IndoorSector, Top, Failure, Zone
from .helper.parser import parse_filters
from .helper.query import query_problems_from_filters
from .helper.grade_order import grades_list
from .statistics.sessions import statistics, base_sessions_stats
from .statistics.gym import current_problems_achievement
from .statistics.sessions import summary


# AutoComplete views

class GymAutocompleteView(autocomplete.Select2QuerySetView):
    
    def get_queryset(self):
        gyms = Gym.objects.all()
        if self.q:
            gyms = gyms.filter(abv__startswith=self.q)
        return gyms

class GymSectorAutocompleteView(autocomplete.Select2QuerySetView):
    
    def get_queryset(self):

        sectors = IndoorSector.objects.all()

        gym = self.forwarded.get('gym', None)
        if gym:
            sectors = sectors.filter(gym__id=gym)

        if self.q:
            sectors = sectors.filter(gym__abv__startswith=self.q)
        return sectors

class ProblemAutocompleteView(autocomplete.Select2QuerySetView):

    re_num = re.compile("^(\d+)(.*)")

    def get_queryset(self):
        problems = IndoorBoulder.objects.all()

        # Forwarded in Session Form
        gym = self.forwarded.get('gym', None)
        if gym:
            problems = problems.filter(gym__id=gym)
        
        sector = self.forwarded.get('sector', None)
        if sector:
            problems = problems.filter(sector__id=sector)
        
        # Forwarded in Try Form --> TODO: why is it not working???
        sess_id = self.forwarded.get('session', None)
        if sess_id:
            gym_id = Session.objects.get(id=sess_id).gym.id
            problems = problems.filter(gym__id=gym_id)

        if self.q:
            m = self.re_num.search(self.q)
            if m:
                sector = m.group(1)
                grade = m.group(2)
                problems = problems.filter(sector__sector_id=int(sector))
            else:
                grade = self.q
            problems = problems.filter(grade__startswith=grade)
        return problems

class GradeAutocompleteView(autocomplete.Select2ListView):

    def get_list(self):

        grades = []
        gym = self.forwarded.get('gym', None)
        if gym:
            grades = grades_list(Gym.objects.get(id=gym), default=True)
        return grades


def index(request):
    # Main page: explore gyms, explore problems, explore sessions, ... -> put in a side menu 
    return HttpResponse("Hello, world. You're at the gymstats index.")

# Homepage view

def __sess(climber: Climber):
    return Session.objects.filter(climber=climber)



def home(request):
    climber = request.user.climber_set.first()
    sessions = {elt.date.strftime("%d/%m/%Y"): (elt.id,) for elt in __sess(climber).only("date")}
    return render(request, 'gymstats/home.html', {'sessions': sessions})


# Profil view

def profil(request):
    climber = request.user.climber_set.first()
    data = {}
    
    # All Time information
    sessions = Session.objects.filter(climber=climber).only("duration")
    data["all_time"] = base_sessions_stats(sessions=sessions)

    today = date.today()
    threshold_positions = climber.thresholds()

    # Month information
    fdom = today.replace(day=1)
    month_sessions = Session.objects.filter(climber=climber, date__gte=fdom)
    data["month"] = statistics(sessions=month_sessions, start_date=fdom, achievements=False,
                               hard_tops=True, threshold_positions=threshold_positions, compute_prev=True)
    # fill target percentages
    data["month"]["training_time_target"] = min(100, data["month"]["duration"] * 100 / climber.month_hour_target)
    data["month"]["hard_boulders_target"] = min(100, data["month"]["hard_tops"] * 100 / climber.month_hard_boulder_target)

    # Year information
    fdoy = today.replace(day=1, month=1)
    year_sessions = Session.objects.filter(climber=climber, date__gte=fdoy).order_by("date")
    
    data["year"] = statistics(sessions=year_sessions, start_date=fdoy, achievements=True,
                              hard_tops=False, threshold_positions=threshold_positions, compute_prev=False)

    # By gym information
    data["by_gym"] = {}
    for gym in climber.preferred_gyms.all():
        data["by_gym"][str(gym)] = current_problems_achievement(gym, climber)

    return render(request, 'gymstats/profil.html', {'data': data, 'climber': climber})


def profil_edit(request):
    climber = request.user.climber_set.first()
    if request.method == 'POST':
        form = ClimberForm(request.POST, instance=climber)
        if form.is_valid():
            instance = form.save()
            return redirect('gs:profil')
    else:
        form = ClimberForm(instance=climber)
        return render(request, 'gymstats/show_form.html', {"current_form": form})


# Statistics views

def stats_searchbar(request):
    return render(request, 'gymstats/stats_searchbar.html')


def stats_display(request):
    if request.method == 'POST':
        climber = request.user.climber_set.first()
        start = request.POST["from"]
        end = request.POST["to"]
        data = _range_stats(climber, start, end)
        return render(request, 'gymstats/stats_display.html', 
                      {
                          "general": data["General"],
                          "achievements": data["Achievements"],
                          "walls": data["Wall Types"],
                          "sw": data["Strengths & Weaknesses"],
                      })


def range_stats(request, range_method):
    climber = request.user.climber_set.first()
    if range_method == "month":
        month = int(request.GET.get("m", date.today().month))
        year = int(request.GET.get("y", date.today().year))
        start = date(day=1, month=month, year=year)
        end = date(day=calendar._monthlen(year, month), month=month, year=year)

    elif range_method == "year":
        year = int(request.GET.get("y", date.today().year))
        start = date(day=1, month=1, year=year)
        end = date(day=31, month=12, year=year)

    elif range_method == "week":
        return JsonResponse({"message": "not yet implemented"})
    
    elif range_method == "range":
        try:
            start = datetime.strptime(request.GET["start"], "%Y-%m-%d")
            if "end" in request.GET:
                end = datetime.strptime(request.GET["end"], "%Y-%m-%d")
            else:
                end = date.today()
        except:
            return JsonResponse({"message": "parsing error..."})
    else:
        return JsonResponse({"message": "method needs to be provided"}) 
    return JsonResponse(_range_stats(climber, start, end), json_dumps_params={'indent': 2})


def _range_stats(climber: Climber, start: date, end: date):
    """
    Compute statistics on given climber's sessions between given start and end dates.
    """
    sessions = Session.objects.filter(climber=climber, date__gte=start, date__lte=end)
    thresholds = climber.thresholds()
    return summary(sessions, thresholds, start)


# Session views

def new_session(request):
    if request.method == 'POST':
        form = SessionForm(request.POST)
        if form.is_valid():
            instance = form.save()
            return redirect('gs:session-add-problems', session_id=instance.id)  # Redirect to a session problem page
    else:
        form = SessionForm()
    return render(request, 'gymstats/new_session.html', {"session_form": form})


def add_session_problems(request, session_id):

    sess = get_object_or_404(Session, id=session_id)
    msg = ""
    success = True
    if request.method == "POST":
        try:
            pb = get_object_or_404(IndoorBoulder, id=request.POST['pb-id'])
            attempts = int(request.POST["attempts"])
            result = request.POST["achievement"]
            if result == "top":
                t = Top(session=sess, attempts=attempts, problem=pb)
            elif result == "zone":
                t = Zone(session=sess, attempts=attempts, problem=pb)
            elif result == "fail":
                t = Failure(session=sess, attempts=attempts, problem=pb)
            else:
                # TODO: error message
                msg = "Unknown achievement..."
                success = False
            if success:
                t.save()
                msg = "achievemement successfully added to current session"
        except ValueError as e:
            msg = "attempts should be a positive integer..."
            success = False
        except KeyError as e:
            msg = "all fields must be filled..."
            success = False

    sectors = IndoorSector.objects.filter(gym=sess.gym)
    sectors_img = set([s.map.url for s in sectors])
    
    # TODO: use sector name
    sectors = {'s:' + str(i + 1): 'Sector ' + str(i + 1) for i in range(sectors.count())}
    grades = {'g:' + g: g for g in grades_list(sess.gym, default=True)}

    problems = {pb: {} for pb in IndoorBoulder.objects.filter(gym=sess.gym, removed=False)}

    return render(request, 'gymstats/add_session_problems.html', {
            "message": {
                "content": msg,
                "success": "yes" if success else "no"
            },
            "session": session,
            "sectors_img": sectors_img,
            "problems": problems,
            "sections": sectors,
        })


def session(request, session_id):
    session = get_object_or_404(Session, id=session_id)
    sess_data = session.statistics()

gymstats/templates/gymstats/add_session_problems.html
{% extends 'gymstats/base_gym_problems.html' %}

{% block title %}Session - Add Problems{% endblock %}

{% block item_info %}
<form method="post" style="display: flex; margin: 5px;">
    {% csrf_token %}
    <input type="hidden" id="pb-id" name="pb-id" value="{{ pb.id }}" />
    <select id="achievement" name="achievement" style="margin-right: 5%;">
        <option value="">---</option>
        <option value="top">Top</option>
        <option value="zone">Zone</option>
        <option value="fail">Fail</option>
    </select>
    <input id="attempts" name="attempts" type="text", placeholder="try.." style="width: 25%;margin-right: 5%;"></input>
    <button type="submit">🚀</button>
</form>
{% endblock %}

gymstats/templates/gymstats/base_gym_problems.html
{% extends 'gymstats/base.html' %}

{% load static %}
{% load custom_filters %}
{% load pb_extras %}


{% block css %}
<link rel="stylesheet" href="{% static 'gymstats/gym_problems.css' %}?ver=1.0">
{{ message|json_script:'message' }}
{% endblock %}


{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'gymstats/collapsible.js' %}?ver=2.2.0" defer></script>
{% endblock %}

{% block content %}
<div class="sector-map" style="display:flex;justify-content: center;">
    {% for img in sectors_img %}
    <img src={{ img }}
        alt="Boulder picture"
        width="45%"
        height="45%"
        style="margin: 20px">
    {% endfor %}
</div>

<div class="problems" style="width:100%">
    <h1>Boulder Problems</h1>
    {% for section, title in sections.items %}
    {% if problems|section_has_problems:section %}
        <button type="button" class="collapsible">{{ title }}</button>
        <div class="content">
            <ul class="gallery"> 
                {% for pb in problems|section_problems:section %}
                <li class="gallery-item">
                    <a href="{% url 'gs:pb-details' pb.id %}">{{ pb|gallery_display }}</a>
                    <img src={{ pb.picture.url }}
                        alt="Boulder picture"
                        width="95%"
                        height="95%">
                    {% block item_info %}
                    {% endblock %}
                </li>
                {% endfor %}  
            </ul>
        </div>
    {% endif %}
    {% endfor %}
</div>

{% endblock %}

gymstats/templates/gymstats/gym.html
{% extends 'gymstats/base_gym_problems.html' %}

{% load static %}

{% block title %} {{gym}} {% endblock %}

gymstats/templates/gymstats/home.html
{% extends 'gymstats/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'gymstats/home.css' %}?ver=1.2.0">
<link rel="stylesheet" href="{% static 'gymstats/calendar.css' %}?ver=1.2.0">
{{ sessions|json_script:'sessions' }}
{% endblock %}


{% block scripts %}
<script src="{% static 'gymstats/calendar.js' %}" defer></script>
{% endblock %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="add-sess">
    <form action="{% url 'gs:session-add-new' %}" method="get">
        <button>Add Session</button>
    </form>
</div>

<div class="calendar-wrapper">
    <header>
        <p class="date"></p>
        <div class="icons">
          <span id="prev" class="material-symbols-rounded">chevron_left</span>
          <span id="next" class="material-symbols-rounded">chevron_right</span>
        </div>
    </header>
    <div class="calendar">
        <ul class="weeks">
            <li>Sun</li>
            <li>Mon</li>
            <li>Tue</li>
            <li>Wed</li>
            <li>Thu</li>
            <li>Fri</li>
            <li>Sat</li>
        </ul>
        <ul class="days" id="days">
        </ul>
    </div>
</div>
{% endblock %}

gymstats/templates/gymstats/problem_results.html
{% extends 'gymstats/base.html' %}

{% load static %}
{% load pb_extras %}

{% block css %}
<link rel="stylesheet" href="{% static 'gymstats/problem_results.css' %}?ver=1.0.1">
<link rel="stylesheet" href="{% static 'gymstats/tagslist.css' %}?ver=1.0.1">
{{ filters|json_script:'filters' }}
{{ stats|json_script:'stats' }}
{% endblock %}

{% block title %} Explorer {% endblock %}

{% block scripts %}
<script src="{% static 'gymstats/filters.js' %}?ver=2.1.13" defer></script>
<script src="{% static 'gymstats/overrepr.js' %}?ver=1.0" defer></script>
{% endblock %}

{% block before %}
<div class="filters">
    <form method=POST action="{% url 'gs:pb-searchresults' %}">
        {% csrf_token %}
        <div class="left" style="width: 60%;">
            <div class="filter-bloc">
                <div class="title">
                    <p>
                        Grades
                        <a class="add-btn">+</a>
                    </p>
                </div>
                <ul class="tagslist filter-list">
                </ul>
            </div>
            <hr>  
            <div class="filter-bloc">
                <div class="title">
                    <p>
                        Gym
                        <a class="add-btn">+</a>
                    </p>
                </div>
                <ul class="tagslist filter-list">
                </ul>
            </div>
            <hr>
            <div class="filter-bloc">
                <div class="title">
                    <p>
                        Attributes
                        <a class="add-btn">+</a>
                    </p>
                </div>
                <ul class="tagslist filter-list">
                </ul>
            </div>
            <hr>
        </div>
        <div class="right" style="width: 35%;">
            <div class="filter-bloc">
                <label class="title" for="current-filter">Currently in Gym</label>
                <input type="checkbox" name="current-filter" id="current-filter">
            </div>
            <hr>
            <div class="filter-bloc">
                <label class="title" for="achievement-filter">Achievement</label>
                <select name="try" id="achievement-filter">
                    <option value="all" selected>All</option>
                    <option value="top">Top</option>
                    <option value="zone">Zone</option>
                    <option value="fail">Fail</option>
                </select>
                <a class="fa fa-chart-line show-stats title" style="margin-left: 10%;"></a>
            </div>                
            <hr>
            <div class="filter-bloc">
            </div>
            <hr>
        </div>
        <hr>
    </form>


</div>
<div class="parse-errors" style="margin-left: 80px;">
    {% if unparsed %}
        <ul>
            {% for u in unparsed %}
                <li>{{ u }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</div>
<div class="statistics">
</div>
<hr class="statistics">
{% endblock %}

{% block content %}
<h3> {{results|length}} problems found. </h3>

{% if results %}
<ul class="gallery">
    {% for problem in results %}
        <li class="gallery-item">
            <a href="{% url 'gs:pb-details' problem.id %}">{{ problem|gallery_display }}</a>
                <img src={{ problem.picture.url }}
                    alt="Boulder picture"
                    width="95%"
                    height="95%">
                <ul class="tagslist">
                    <li class="small ty">{{ problem.wall_angle }}</li>
                    {% for h in problem|hh %}
                        <li class="small hh">{{ h }}</li>
                    {% endfor %}
                    {% for f in problem|fw %}
                        <li class="small fw">{{ f }}</li>
                    {% endfor %}
                    {% for m in problem|me %}
                        <li class="small me">{{ m }}</li>
                    {% endfor %}
                </ul>
        </li>
    {% endfor %}
</ul>
{% else %}
    <p>No problems stored.</p>
{% endif %}
{% endblock %}

gymstats/templates/gymstats/problem_searchbar.html
{% extends 'gymstats/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'gymstats/searchbar.css' %}?ver=1.0">
{% endblock %}

{% block title %}Explorer{% endblock %}

{% block scripts %}
<script src="{% static 'gymstats/explorer.js' %}" defer></script>
{% endblock %}

{% block content %}
<h1 class="title"> <i class="fa fa-earth-europe"></i> Problem Explorer <i class="fa fa-earth-europe"></i></h1>
<form method=POST action="{% url 'gs:pb-searchresults' %}">
    {% csrf_token %}
    <input id="searchbar" class="searchbar" type="search"
    name="search" placeholder="Search problems..">
</form>
{% endblock %}

gymstats/templates/gymstats/profil.html
{% extends 'gymstats/base.html' %}

{% load static %}
{% load custom_filters %}
{% load pb_extras %}

{% block css %}
<link rel="stylesheet" href="{% static 'gymstats/tab.css' %}?ver=1.0">
<link rel="stylesheet" href="{% static 'gymstats/profil.css' %}?ver=1.2.0">
{{ data|json_script:'data' }}
{% endblock %}

{% block title %}Profil{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="{% static 'gymstats/profil.js' %}?ver=2.4.4" defer></script>
<script src="{% static 'gymstats/change_tab.js' %}?ver=1.0.1" defer></script>
{% endblock %}

{% block content %}
<div class="profil">
    <img src={{ climber.picture.url }}
    alt="Profil Picture"
    width="80"
    height="80"
    style="border-radius: 100%; margin-right: 20px;">
    <h1 style="vertical-align: middle;">{{ climber }}</h1>
    <h1 style="vertical-align: middle; margin-left: auto; margin-right: 0;"><a style="text-decoration: none;" href="{% url 'gs:profil-edit' %}" class="fa fa-sliders"></a></h1>
</div>

<div class="all-time">
</div>

<div class="month box">
    <p style="text-align: center;">This month</p>

    <div class="month-progress">
        <svg class="progress time">
            <text text-anchor="middle" x="100" y="110" style="font-size:40px">&#128337;</text>
            <circle class="bg" cx="100" cy="100" r="90" />
            <circle class="progress-bar" cx="100" cy="100" r="90" />
            <text text-anchor="middle" class="btm-text" x="100" y="215" style="font-size:15px">Training time: </text>
        </svg>
        <svg class="progress tops">
            <text class="center-image" text-anchor="middle" x="100" y="110" style="font-size:40px"></text>
            <circle class="bg" cx="100" cy="100" r="90" />
            <circle class="progress-bar" cx="100" cy="100" r="90" />
            <text text-anchor="middle" class="btm-text" x="100" y="215" style="font-size:15px">Hard boulders: </text>
        </svg>
    </div>
</div>
        
<div class="year box">
    <p style="text-align: center;">Year problems by difficulty</p>

    <div class="tab">
        <button class="tablinks" id="defaultOpen" data-id="all-pb">All</button>
        <button class="tablinks" data-id="lower-pb">Lower</button>
        <button class="tablinks" data-id="expect-pb">Expect</button>
        <button class="tablinks" data-id="higher-pb">Higher</button>
        <button class="tablinks" data-id="unk-pb">Unk</button>
    </div>

    <div id="all-pb" class="statstab">
        <canvas id="year-all-problems"></canvas>
    </div>
    <div id="lower-pb" class="statstab">
        <canvas id="year-lower-problems"></canvas>
    </div>
    <div id="expect-pb" class="statstab">
        <canvas id="year-expect-problems"></canvas>
    </div>
    <div id="higher-pb" class="statstab">
        <canvas id="year-higher-problems"></canvas>
    </div>
    <div id="unk-pb" class="statstab">
        <canvas id="year-unk-problems"></canvas>
    </div>
</div>

<div class="by-gym-stats box">
    <label for="gym-select">Gym:</label>
    <select name="gym" class="gym-select">
        <option value="">--select gym--</option>
    </select>
    <div>
        <canvas id="gym-stats"></canvas>
    </div>
</div>

<div class="shoe-usage box">
    TODO fill shoe usage histogram
</div>
{% endblock %}

gymstats/templates/gymstats/reviews_list.html
{% extends 'gymstats/base.html' %}

{% block content %}
{% if reviews_list %}
    <ul>
    {% for review in reviews_list %}
        <li><a href="/gymstats/problems/{{ problem.id }}/reviews/{{ review.id }}">{{ review }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No reviews for this problem</p>
{% endif %}
{% endblock %}